### ISSUE TITLE
Exposure time set vs real exposure time

### ISSUE THREAD

**Issue by 3git** [KonradIT/autoexechack#23]
Hi Konrad, 

First of all thanks for your effort in making all those gopro hacks- I found them very useful. I'm a bit concerned however about the exposure time- I used the table and updated the ash file as described, however it still seem that gopro uses different (shorter) exposure time. File EXIF shows e.g exp as 7,7 seconds, but if you look at the picture it's definietly shorter. I used Syma X5C-1 quadcopter to do some awesome effects (thay are still awesome thanks to your hack!) but I am pretty sure I'd fly much more within 7,7 secs- this looks more like 3 seconds maximum. 

Did anyone reported this already? Tried to search for something but I'm new on GitHub and didn't have enough luck yet to resolve it. I tried with a bit lower exposure time (still around 6-7 secs) and it's the same. I have GP H3+ Black. 

![capture2](https://cloud.githubusercontent.com/assets/10708826/5900890/f846b26a-a56d-11e4-8e34-813f5d4b0e84.JPG)

![capture](https://cloud.githubusercontent.com/assets/10708826/5900893/fe8e92b4-a56d-11e4-85a8-a3df8b16a424.JPG)

.

**Comment by KonradIT** [comment]
Yes, around 7 seconds it shortens it to 5 seconds.
