### ISSUE TITLE
Doesn't work on GoPro Hero4 Silver

### ISSUE THREAD

**Issue by oli-z** [KonradIT/autoexechack#29]
The scripts for the GoPro 4 (https://github.com/KonradIT/autoexechack/tree/GoPro/HERO4) are not working on my GoPro 4 Silver. I've also tried different SD cards.

**Comment by KonradIT** [comment]
Yes, I know. HERO4 do not execute autoexec.ash :((

**Comment by richdale** [comment]
Konrad I am confused why you have HERO4 autoexec.ash scripts in your repos if there is no support for running them on HERO4.  Is there a non-official firmware release that does????
