### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by robyr1** [KonradIT/autoexechack#3]
I tried on my hero3+ black, it doesn't work!

**Comment by KonradIT** [comment]
@robyr1, which hack does not work? Make sure the file is named autoexec.ash, no autoexec.ash.txt or other.
Also, make sure you copied it to the root of the sd.

**Comment by robyr1** [comment]
these 2 files doesn't works:
https://github.com/KonradIT/autoexechack/tree/GoPro/LockVideoExposure
and
https://github.com/KonradIT/autoexechack/tree/GoPro/AE-Video/HERO3PlusBlack
i tried some of others, and works (not all!) and i'm pretty sure that i doesn't changed/renamed the file, also is on the root of the card...but simply doesn't work!

**Comment by KonradIT** [comment]
On Lock exp: put your hand in the lens of the gopro, turn it on, start recording, wait two seconds, remove the hand and all the footage is locked-exposed.
Auto Exposure is hard to notice in the video, I coded it for a timelapse, there were a lot of tunnels, constant change of light...
Which hack works on H3+b and which hacks not? I dont own a hero3+black, so if you could tell me, i will really appreciate it!

**Comment by robyr1** [comment]
Here are one file that it doesn't work:
https://github.com/KonradIT/autoexechack/tree/GoPro/HDRPhoto/HERO3PlusBlack
I tried on two different cameras!

**Comment by KonradIT** [comment]
Thanks for the input

**Comment by digitalanthill** [comment]
Hey, how do I download the autoexec.ash file from here. By clicking the link it just opens the file within the site?!

**Comment by KonradIT** [comment]
@digitalanthill check [this howto](https://gist.github.com/KonradIT/ce55b04ab4ad10592ebf/#file-autoexechack-md) You should also read the Readme.md

**Comment by digitalanthill** [comment]
Thanks for the quick response. Doing it this way worked perfectly. Is 8 days the longest you've had a time-lapse running using this method?

**Comment by KonradIT** [comment]
@digitalanthill I decided to shoot for 8 days because I want to use my GoPro. Also this was a test, since two weeks, my camera is out hacked with 13 min interval to shoot for a month. The intervals can be from 1 second to 45 minutes (in seconds!).

**Comment by alongoria88** [comment]
When I right-click the RAW button, I only the the option to "save link as." What else can I do to download the file?

**Comment by KonradIT** [comment]
@alongoria88 read [this](https://gist.github.com/KonradIT/ce55b04ab4ad10592ebf/#file-autoexechack-md)
