### ISSUE TITLE
Alter the rec-button behaviour?

### ISSUE THREAD

**Issue by sirtet** [KonradIT/autoexechack#32]
A question to the hackers:
How hard would it be to modify the behaviour of the rec button to "record while pressed"?

What for should it be done:
With the Cam on a helmet, one is never shure if it's rolling or not.
So, having a switch vs. a button would be more intuitive, you could feel "left = rec. right = pause".

A mechanical extension to the gopro case would be fairly easy to do, maybe 3d-printable.
A knob that can be slid over the rec. button, which would permanently press the button.

But the difficult question is, can the firmware be modified, so that a permanent press (starting at longer than X seconds) would start record, until button releases.

I even reached out to GoPro with that idea, but they showed no interest...

So, maybe hackers here could help out with some infos about how hard it would be to do?

**Comment by KonradIT** [comment]
With autoexec.ash is not possible to even get the click event

**Comment by vojtaripa** [comment]
does the code work differently with gopro4 silver? Thank you,Vojta Ripa

```
 On Tuesday, March 24, 2015 12:10 PM, Konrad Iturbe <notifications@github.com> wrote:
```

 With autoexec.ash is not possible to even get the click event—
