### ISSUE TITLE
Timelapse everytime stop at 51 shots

### ISSUE THREAD

**Issue by tomaszterka** [KonradIT/autoexechack#33]
Hi,
Like i write in title timelapse everytime stop at 51 shots (using 5 sec timelapse file for HERO 2014 1.07 firmware). I tryed put some lover numers than 4  but still the same. Someone else have this problem?

**Comment by tomaszterka** [comment]
I think this is solution  for my problem. I just take config from NightLapse and delete line with ISO, exp and all works fine. For example here is config for 5sec Timelapse:

sleep 1
t app key mode
sleep 1
t app key record
sleep 1
reboot yes

I counted also time needed for reboot so this giving u +/- 5 sec

**Comment by ghost** [comment]
Will look at it tomorrow, thanks!
Konrad Iturbe 
Madrid, Spain. 
http://chernowii.com
Sent using CloudMagic
On Thu, Apr 02, 2015 at 9:42 PM, tomaszterka notifications@github.com wrote:I think this is solution  for my problem. I just take config from NightLapse and delete line with ISO, exp and all works fine. For example here is config for 5sec Timelapse:

sleep 1
t app key mode
sleep 1
t app key record
sleep 1
reboot yes

I counted also time needed for reboot so this giving u +/- 5 sec

**Comment by vicloro91** [comment]
Hello,
not if I passed, but the timelapse file runs only 51 times , only makes 51 photos.
playing some file got it reached 10,000 approx.
I have done it if you're interested , repeating the code sleep ... t app key 180 times in a file ( not because it leaves me repeat more times ( the camera does not support it ?)) .
So I get to do 180 pictures before the restart file timelapse.ahs
The version is the last one was released . The camera is 1.07 and the hero 2014

**Comment by tomaszterka** [comment]
I can check it if u have better idea :)

**Comment by KonradIT** [comment]
@tomaszterka Hi. Thanks for the correction, I did a time lapse.ash file to avoid any problems but it seems it does not work. Will update the project. I haven't got a Hero 2014 so I can't test the other intervals, could you test this please:

10 seconds interval:

sleep 1
t app key mode
sleep 5
t app key record
sleep 1
reboot yes

30 seconds interval:

sleep 1
t app key mode
sleep 25
t app key record
sleep 1
reboot yes

Best regards

**Comment by tomaszterka** [comment]
Ok i will test this. On 5 sec interval like i write before i recorded 16 min and iv got somthing like 200 pictures and all works fine. But will test a little more :)

**Comment by vicloro91** [comment]
stops when it reaches 581 photos.
knowing that makes 581 reboots and 51 readings timelapse file, I have implemented the following code , which I tested and it works.
reaches 51 photos and restarts, and 51 more restarts , so by logic we would have 581 \* 51 = 29000 approx.
sleep 5
t app key record
sleep 5
d:\timelapse.ash
reboot yes

**Comment by tomaszterka** [comment]
Just checked this code (10 sec):

sleep 1
t app key mode
sleep 5
t app key record
sleep 1
reboot yes

2h of shooting
665 photos 

and all still working fine :)

**Comment by ghost** [comment]
For me the 10 sec interval works also perfect! My only question is if continuous reboot harms the camera. Do you guys have an idea about it?

**Comment by ghost** [comment]
@dantypas2 It should not harm the camera as long as the picture is progressed correctly.
Sent using Boxer
On May 9, 2015 2:33 PM, dantypas2 notifications@github.com wrote:For me the 10 sec interval works also perfect! My only question is if continious reboot harms the camera. Do you guys have an idea about it?
