### ISSUE TITLE
HERO 1080 60 fps ?

### ISSUE THREAD

**Issue by tomaszterka** [KonradIT/autoexechack#34]
Probably u heared about new GoPro HERO+ LCD. One of the feature is 1080 60 fps. In my opinion this stil the same camera like HERO. What u think they can make update for HERO with 1080 60 fps or if no  is any chance to copy  from HERO+ that option and put in HERO?

**Comment by KonradIT** [comment]
Looking at the firmware, it does not seem to have a specific command to change frame rate and I am not a **real programmer** who uses a magnetized needle and a steady hand to hardcode the firmware.
