### ISSUE TITLE
Loop video on Hero2

### ISSUE THREAD

**Issue by krocebow** [KonradIT/autoexechack#35]
Hi everyone,

I've got a problem with my Hero2, I'm trying to use this loop video script : 
https://github.com/KonradIT/autoexechack/tree/GoPro/HERO2Autoexec/LoopVideo

But it doesn't work, I used the 198 & 222 firmeware but my camera freezes and the only way to get it to work is to update to the latest firmeware.

I verified the extention of the autoexec file and it's .ash not .ash.txt but still don't work.

This is the content of the file : 
t gpio 43 sw out0
sleep 900
t gpio 43 sw out1
t gpio 43 sw out0
d:\autoexec.ash
reboot yes

Anyone  can help please?

Thanks.

**Comment by KonradIT** [comment]
[Fixed!](https://github.com/KonradIT/autoexechack/commit/4efe82431d1f0401678c7ad61b41ed472ec97d3e)

**Comment by coalsi** [comment]
Same problem, what was the fix?
