### ISSUE TITLE
Didn't work Exposure Video Lock

### ISSUE THREAD

**Issue by artemaminov** [KonradIT/autoexechack#36]
I've Hero3+ Black upgraded to 3.0 firmware version. Did LockVideoExposure hack work on that firmware? autoexec.ash file is at root folder and lens covered to dark for 7 secs after rec button pushed.

**Comment by artemaminov** [comment]
Downgraded to 2.0, still no lock.

**Comment by KonradIT** [comment]
Does any hack work on your camera? Try the led one

**Comment by artemaminov** [comment]
LED Dance didn't work too

**Comment by allemyr** [comment]
Hi again Konrad Iturbe!

Hope everything is good with you! :)

LED dance work for me :) on 3+ Black edition

I read on the forum a while ago that you found it impossible to set manual exposure on Gopro cameras in video mode, I understand that it's a tuff jobb doing this code.
I'am far away a coder myself but I do like Gopros and film/video a lot. But I find it a bit odd from Gopros side to just be able to restrict ISO between 100 and 400.
Sorry for saying this again but it would be super cool to set ISO 100 for video clips. Tried to se the exif data for video clips from my Gopro but I find it only possible to view the exif data from photos.

Kind regards

Karl Allemyr

**Comment by KonradIT** [comment]
@allemyr lowest is [400](http://cbcdn1.gp-static.com/uploads/product_manual/file/202/HERO3_Plus_Black_UM_ENG_REVD.pdf#page=41&zoom=auto,-305,45)

**Comment by artemaminov** [comment]
@allemyr which version firmware do you use?
