### ISSUE TITLE
Don't work in HD3.11.03.00 (GoPro HERO3+ Black Edition)

### ISSUE THREAD

**Issue by nook-scheel** [KonradIT/autoexechack#38]

**Comment by nook-scheel** [comment]
Downgrade to HD3.11.02.00 and don't work. But when you first start the firmware script is run! After the restart does not start

**Comment by nook-scheel** [comment]
It works with memory stick 16 GB! Prior to that used Lexar X600

**Comment by nook-scheel** [comment]
![Image of Yaktocat](https://s3.amazonaws.com/f.cl.ly/items/0Y2d1k3y1x1P3R1e0e3t/GOPR3457.jpg)

**Comment by KonradIT** [comment]
So, it works now!
