### ISSUE TITLE
autoexechack/LongExpTimeLapse

### ISSUE THREAD

**Issue by vicloro91** [KonradIT/autoexechack#39]
buenas tardes konrad!
He estado probando el autoexec del longexp.. en la hero 3+silver , y hay algo que no acaba de funcionar. 
La enciedo,pasa al modo foto, hace una foto normal, (poniendo la x a 2), sleep y reinicio.

Alguna idea?

**Comment by ghost** [comment]
La hero3+silver no soporta el comando que pone el valor de la exposición.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.0.42&pv=5.1.1] On Mon, Aug 03, 2015 at 8:02 PM, vicloro91 < notifications@github.com [notifications@github.com] > wrote:
buenas tardes konrad!
He estado probando el autoexec del longexp.. en la hero 3+silver , y hay algo
que no acaba de funcionar.
La enciedo,pasa al modo foto, hace una foto normal, (poniendo la x a 2), sleep y
reinicio.

Alguna idea?
