### ISSUE TITLE
Hero3 Silver LongExp not working

### ISSUE THREAD

**Issue by raelschiffler** [KonradIT/autoexechack#46]
Hello bud, you're my hero. Thanks for helping so much people. 
My issue is that the script didn't work in my cam.
"firmware version":"HD3.02.03.00",
"wifi version":"3.4.2.18",
"wifi bootloader version":"0.2.2",
"camera type":"Hero3-Silver Edition",

The code I used is:
t gpio 43 sw out0
t ia2 -ae still_exp 100 5 15
sleep 10
t gpio 43 sw out1
t gpio 43 sw out0
d:\autoexec.ash
reboot yes 

I really believe my cam doesn't process the line 2 
t ia2 -ae still_exp 100 5 15 ,
because it takes effectively a shot each 10 secs as set, but the iso and the exp remain auto (the cam sets the values according to its own algorithm). 

Thanks for your attention.

**Comment by seanotoole23** [comment]
would love help with this problem as well

**Comment by Hamel-Eng** [comment]
Hi, I have also come to this conclusion, after a long time trying to figuring it out.
when i check the exif data it shows that the camera has taken the photo on auto.

Did you get any further with this? it feels like we are so close...

Cheers

(Hero3 Silver, fw: 3.0)

**Comment by seanotoole23** [comment]
I did not  all I know is it would just shut off at random then start over
heating

**Comment by Hamel-Eng** [comment]
I see, I'll try and find out a bit more.
Thanks for the reply.

**Comment by seanotoole23** [comment]
No problem was Geting a little display glitching as well at one point

**Comment by KonradIT** [comment]
Neither the HERO3 Silver, White or HERO4 Session allow the "t ia2" command that changes exposure to work. Thread closed.
