### ISSUE TITLE
Preview Video Resolution Change

### ISSUE THREAD

**Issue by jstromsoe** [KonradIT/autoexechack#58]
Current resolution on the streaming preview for GoPro Hero 4 Black is something like 240p and only lasts for 12s without the use of a Python script in the background.  Ideally there would be a way to stream this video at least 720p and not have to use a Python script.  Seems like there must be a hidden setting to do this.  Thoughts?

Check this out for more details.  

https://www.reddit.com/r/gopro/comments/2md8hm/how_to_livestream_from_a_gopro_hero4/

**Comment by KonradIT** [comment]
You mean because of Periscope? Periscope resizes the stream to 720p
