### ISSUE TITLE
protune photo and parameters

### ISSUE THREAD

**Issue by firebird123** [KonradIT/autoexechack#6]
hi there :)
protune photo dont work ( hero 3 black edition )

<code>sleep 1</code>
<code>t ia2 -3a 1 0 1 1</code>

but hdr photo is work.

<code>t app appmode photo</code>
<code>sleep 1</code>
<code>t ia2 -3a 0 1 0 1</code>
<code>t app button shutter PR</code>
<code>sleep 2</code>
<code>t ia2 -3a 1 0 1 0</code>
<code>t app button shutter PR</code>
<code>sleep 2</code>
<code>t ia2 -3a 0</code>
<code>t app button shutter PR</code>

this [ia2 -3a] all parameters can learn from it? 
because it turns out that some photos in few daylight only white.

t ia2 -3a ? ? ? ?

Thanks

**Comment by KonradIT** [comment]
Hi. Thanks for the input.
